export const COUNTRY_CODE = {
  "AN":"andaman and nicobar islands",
  "AP":"andhra pradesh",
  "AR":"arunachal pradesh",
  "AS":"assam",
  "BR":"bihar",
  "CH":"chandigarh",
  "CT":"chattisgarh",
  "DL":"delhi",
  "DN":"dadra and nagar haveli and daman and diu",
  "GA":"goa",
  "GJ":"gujarat",
  "HP":"himachal pradesh",
  "HR":"haryana",
  "JH":"jharkhand",
  "JK":"jammu and kashmir",
  "KA":"karnataka",
  "KL":"kerala",
  "LA":"ladakh",
  "MH":"maharasthra",
  "ML":"meghalaya",
  "MN":"manipur",
  "MP":"madhya pradesh",
  "MZ":"mizoram",
  "NL":"nagaland",
  "OR":"odisha",
  "PB":"punjab",
  "PY":"puducherry",
  "RJ":"rajasthan",
  "SK":"sikkim",
  "TG":"telangana",
  "TN":"tamil nadu",
  "TR":"tripura",
  "TT":"india",
  "UP":"uttar pradesh",
  "UT":"uttarakhand",
  "WB":"west bengal"
}
